FROM tiangolo/uwsgi-nginx-flask:python3.8
ARG VERSION=unknown

LABEL maintainer="eduard.c.staniloiu@gmail.com" \
      name="Demo Flask App" \
      version="${VERSION}"

# Create app directory
WORKDIR /app
